name: dependents_example
publish_to: "none"
description: Example app for the dependents package
version: 1.0.0

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependents:
    path: ../
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
